services:
- docker
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.27.4
  - secure: O1xidj4tcsKWEdlKecjk+FRjnRdHPgKQgQXufjrW5MC+eIev0Oe9DjEWl5NemCs9b7Ted8CCeqTpcWPUqf3LmZ63BPBacOi8+kN9WOGlXGPsOqqUYq6YvwjhUmZW5xfMYAftBwGGLN1KmpRBX32XLHClawyNMTAxBKPyXCC82u5GDuD/RTN93abn60HKgE5OguLs4A3p6WsCnYiNIgTieHSOHxHcqXXj0XqO7XWid42WustYgU0qUHJhBnbDsaey6iGFtiJ/QF/VDD7s7uOfIv+6Bu3y9u4SWFr2GsdvdREe4FyTzE9S/Ys5bqwwCdvvni+vH0wvMqtghiQ0Wk5LHuzVYSuXZ3xyV1k/w5tBBU33QT47oBHxqmk6h93GFJxIMlQtaWKmbLxrK5OmdNArYuQIOgCiHcH5cOh7SxjvkLSWLXLaz+LivUMjOnxmcKiwJcrW9ZN/9AOm50n/TLmna+x6Bn3eNWZP61/1VdHykQzys2NfBqz2IqUGaDTHeaH+zXzhP6h8fbswaVUifhopsvNWVRRR3m+LB5EvYjscd5ebnTOQS8ck+Ly/MFtuKLD/uJEavgiFMmwBW4/sEZxzHLlLGzPdsi+JtFlPSZVhHXAThrBE6ZsF8oirHMdLd70IdiHEsEgq5k1e6h6VGGvt+F+dzRZfhcakKHITXmLkhJw=
  - secure: rAtGGUR3IRjIihvLQl/fD4A9dmSNnP+OfghIEilxfBi1LD0ojCYPes97em4SCAL6Nh1QO5SMJTj/g+N+cKvK/EAMB5uaZkwQh3fFrwx3dyLJ3RRGWmkqb047GLe/pdm7W3clECYmdo+zcKwnuXLWfFRCCaHtf58iaNvG5QSyyj+AM6hSFVrq6pFQYcvowIf0gW2uH7ClA4wtfcg/6l83SbPwkc72/8is6a857Xx1u/QPBzkn/QtBJvzuTohmNwwVEyc+uvOfP+40lL3wg64sR6On/zRTnN+iMS3eFd7UrnEIFqOHRrPs36/1nT9pKQLfiPow+DYIrABlOujhj/TvjVJq9lMK2POrz4dBdT2QtF6kZdniBA+ZKH4Lp8Ool7XF7VFqb78+TTCOn0O1G7BGN/t+X55GtNoEdoPajD16sT62a3zmIu96WqlRds87gFzVlXIZnUMBodMR201vBYUYKOao5P+Pjcs3IgRVS9GEqXSkaEc/aha+6Dvm6WHyuOJ4q/9YZw9bju0R/Qn9xLkdI3nwfVHHC4abi/B7Ihfs/c5MVNChV1lT866eOlZyUYbLWvVe1qvHHL+yJzcDx6dse9EYYqL/8xGG0758tqjFDlgaisX1AuCSfI7vbTAFiuPFyMdqlrzsfxvZ5i4dDiVkkZKo5OEVQGyoN/nF+g6FL3I=
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker --version
- docker-compose version
- echo "Login into Docker Hub"
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- export GIT_SHA=`git rev-parse --short HEAD`
- echo "Building commit $GIT_SHA"
jobs:
  include:
  - stage: tests
    name: Compelete test
    script:
    - bin/up
    - bin/build
    - bin/test
  - stage: push_server
    script:
    - docker-compose up backend
    - docker tag todo_backend:latest andyphied/todo_backend:$GIT_SHA
    - docker push andyphied/todo_backend:$GIT_SHA
    - docker tag todo_backend:latest andyphied/todo_backend:$TRAVIS_BRANCH
    deploy:
    - provider: script
      script: docker push andyphied/todo_backend:$TRAVIS_BRANCH
      on:
        branch: master
    - provider: script
      script: docker push andyphied/todo_backend:$TRAVIS_TAG
      on:
        tags: true
  - stage: push_frontend
    script:
    - docker-compose up frontend
    - docker tag todo_frontend:latest andyphied/todo_frontend:$GIT_SHA
    - docker push andyphied/todo_frontend:$GIT_SHA
    - docker tag todo_frontend:latest andyphied/todo_frontend:$TRAVIS_BRANCH
    deploy:
    - provider: script
      script: docker push andyphied/todo_frontend:$TRAVIS_BRANCH
      on:
        branch: master
    - provider: script
      script: docker push andyphied/todo_frontend:$TRAVIS_TAG
      on:
        tags: true
  - stage: push_search
    script:
    - docker-compose up search
    - docker tag todo_search:latest andyphied/todo_search:$GIT_SHA
    - docker push andyphied/todo_search:$GIT_SHA
    - docker tag todo_search:latest andyphied/todo_search:$TRAVIS_BRANCH
    deploy:
    - provider: script
      script: docker push andyphied/todo_search:$TRAVIS_BRANCH
      on:
        branch: master
    - provider: script
      script: docker push andyphied/todo_search:$TRAVIS_TAG
      on:
        tags: true
